---
- name: Configurações comuns para todos os nós 
  hosts: all
  become: yes
  tasks:
    - name: Atualizar cache de pacotes
      apt:
        update_cache: yes

    - name: Instalar pacotes adicionais
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common

    - name: Criar dir keyrings
      ansible.builtin.shell:
        cmd: sudo install -m 0755 -d /etc/apt/keyrings

#    - name: Adicionar chave GPG Docker 
#      apt_key:
#        url: https://download.docker.com/linux/ubuntu/gpg 
#        state: present
    - name: Adicionar chave do repo Docker 
      ansible.builtin.shell:
        cmd: sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc

    - name: Ajustar permissoes de keyring Docker
      ansible.builtin.shell: 
        cmd: sudo chmod a+r /etc/apt/keyrings/docker.asc

    - name: Adicionar repositório Docker 
      apt_repository:
        repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu jammy stable
        state: present
        filename: docker

    - name: Instalar Docker 
      apt:
        name: docker-ce 
        state: present

    - name: Iniciar e habilitar serviço Docker 
      systemd:
        name: docker 
        state: started
        enabled: yes

    - name: Adicionar chave GPG Kubernetes 
      #apt_key:
      #  url: https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key
      #  state: present
      ansible.builtin.shell:
        cmd: sudo curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg 
    
    - name: Ajustar permissoes de keyring Kubernetes
      ansible.builtin.shell: 
        cmd: sudo chmod a+r /etc/apt/keyrings/kubernetes-apt-keyring.gpg

    - name: Adicionar repositório Kubernetes
      apt_repository:
        repo: deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /
        state: present
        filename: kubernetes

    - name: Instalar pacotes Kubernetes
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - kubelet
        - kubeadm
        - kubectl

    - name: Fixar versão dos pacotes Kubernetes
      dpkg_selections:
        name: "{{ item }}"
        selection: hold
      loop:
        - kubelet
        - kubeadm
        - kubectl

    - name: Desativar swap 
      command: swapoff -a
      when: ansible_swaptotal_mb > 0

    - name: Remover entradas de swap do /etc/fstab 
      replace:
        path: /etc/fstab
        regexp: '^([^#].*?\sswap\s+.*)$'
        replace: '# \1'

    - name: Configurar módulos de kernel para kubernetes
      copy:
        dest: /etc/modules-load.d/k8s.conf 
        content: |
          br_netfilter
          overlay

    - name: Carregar módulos de kernel
      command: "{{ item }}"
      loop:
        - modprobe br_netfilter
        - modprobe overlay

    - name: Configurar sysctl para Kubernetes
      copy:
        dest: /etc/sysctl.d/k8s.conf 
        content: |
          net.bridge.bridge-nf-call-iptables = 1
          net.bridge.bridge-nf-call-ip6tables = 1
          net.ipv4.ip_forward = 1

- name: Configurar nó master do Kubernetes
  hosts: masters
  become: yes 
  tasks: 
    - name: Iniciar cluster Kubernetes
      command: kubeadm init --pod-network-cidr=10.244.0.0/16 
      register: kubeadm_init_output 

    - name: Criar diretório .kube para usuário vagrant
      file: 
        path: /home/vagrant/.kube 
        state: directory 
        owner: vagrant
        group: vagrant

    - name: Copiar arquivo de configuração do kubernetes para o usuário vagrant
      copy:
        src: /etc/kubernetes/admin.conf 
        dest: /home/vagrant/.kube/config 
        remote_src: yes 
        owner: vagrant 
        group: vagrant

    - name: Instalar rede Flannel para o cluster
      become: no 
      command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml 
      environment:
        KUBECONFIG: /home/vagrant/.kube/config 

    - name: Gerar comando de join para workers
      command: kubeadm token create --print-join-command
      register: join_command

- name: Configurar nós workers do Kubernetes
  hosts: workers
  become: yes
  tasks: 
    - name: Juntar-se ao cluster Kubernetes
      command: "{{ hostvars['k8s-master']['join_command'] }}"
      register: join_output
      failed_when: false


